# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
     pod 'Firebase/Auth'
     pod 'Firebase/Database'
     pod 'FacebookCore'
     pod 'FacebookLogin'
     pod 'FacebookShare'
     pod 'FBSDKLoginKit'
     pod 'Firebase/Core'
     pod 'Firebase/Analytics'
     pod 'Firebase/Messaging'
     pod 'ImageSlideshow', '~> 1.4'
target 'WildcatLibrary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'ImageSlideshow', '~> 1.4'

  # Pods for WildcatLibrary

  target 'WildcatLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WildcatLibraryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
