# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Picket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Picket

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'SwiftMessages'
  pod 'ImagePicker'
  pod 'TPKeyboardAvoiding'
  pod 'SwiftGifOrigin', '~> 1.6.1'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'Firebase/Storage'
  pod ‘Firebase/Auth’

  target 'PicketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PicketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
