# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FabulaFirebase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FabulaFirebase
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/AppIndexing'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  
  target 'FabulaFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FabulaFirebaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
