# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BLAuctions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BLAuctions
pod 'Eureka', '~> 2.0.0-beta.1'
pod 'ImageRow', '~> 1.0'
pod 'NVActivityIndicatorView'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'AWSCognito'
pod 'BraintreeDropIn'
pod 'SkyFloatingLabelTextField', '~> 2.0.0'
pod 'TagListView', '~> 1.0'
pod 'Braintree/PayPal'
pod 'Braintree/Venmo'
pod 'Braintree/Apple-Pay'
pod 'Braintree/3D-Secure'
  target 'BLAuctionsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
